name: CI for Web extension

on:
  pull_request:
    paths:
      - .github/workflows/ci-ext.yaml
      - .github/workflows/codeql.yaml
      - .github/workflows/lcm.yaml
      - Extension/**
      - .editorconfig
      - .prettierignore
      - .prettierrc.json
      - eslint.config.mjs
      - justfile
      - package-lock.json
      - package.json
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "PATH=$PATH" >> $GITHUB_ENV
          brew install just
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Build
        run: just extension

  format:
    runs-on: ubuntu-24.04
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "PATH=$PATH" >> $GITHUB_ENV
          brew install just
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Check formatting
        # TODO: check format other should be run for everything except swift code
        run: just check-format-other

  lint:
    runs-on: ubuntu-24.04
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "PATH=$PATH" >> $GITHUB_ENV
          brew install just
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Check linting
        run: just check-lint-npm

  test:
    runs-on: ubuntu-24.04
    env:
      GABBER_CI: "true"
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
      - name: Setup build tools
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "PATH=$PATH" >> $GITHUB_ENV
          brew install just
      - name: Setup npm dependencies
        run: |
          npm ci
      - name: Test extension
        run: just test-extension
